import { test, expect } from '@playwright/test';
import type { RoomView, Session } from '../src/server/types';
import { specialUsage } from '../src/game/playerStats';
test('相手の宝石・使用数とターンごとの対戦ラインを確認できる', async ({ page, request }) => {
  async function action(data: object, session?: Session) {
    const response = await request.post('/api/rooms', { headers: session ? { Authorization: `Bearer ${session.token}` } : {}, data: { ...data, ...(session ? { code: session.code } : {}) } });
    expect(response.ok(), await response.text()).toBeTruthy(); return response.json();
  }
  async function get(session: Session): Promise<RoomView> {
    const response = await request.get(`/api/rooms?code=${session.code}`, { headers: { Authorization: `Bearer ${session.token}` } });
    return response.json();
  }
  const host: Session = await action({ action: 'create', humanCount: 2, name: 'アカリ' });
  const guest: Session = await action({ action: 'join', code: host.code, name: 'ソラ' });
  const start: RoomView = await action({ action: 'start' }, host);
  const p0 = start.game!.players[0], p1 = start.game!.players[1];
  await action({ action: 'select', selection: [{ ...p0.bag.find(d => d.kind === 'ruby')!, value: 6 }, { ...p0.bag.find(d => d.kind === 'thief')!, value: 0 }] }, host);
  const before = await get(guest);
  expect(specialUsage(before.game!.players[0]).find(s => s.kind === 'thief')!.used).toBe(0);
  await action({ action: 'select', selection: [{ ...p1.bag.find(d => d.kind === 'poison')!, value: 0 }, { ...p1.bag.find(d => d.kind === 'mining')!, value: 0 }] }, guest);
  const countdown = await get(guest);
  expect(countdown.game!.phase).toBe('reveal');
  expect(specialUsage(countdown.game!.players[0]).find(s => s.kind === 'thief')!.used).toBe(0);
  await expect.poll(async () => (await get(guest)).game!.phase, { timeout: 10000, intervals: [500] }).toBe('inspect');
  const inspected = await get(guest);
  expect(Object.keys(inspected.game!.selections)).toHaveLength(4);
  expect(inspected.game!.players[0].jewels).toHaveLength(0);
  expect(inspected.game!.visualEvents).toEqual([]);
  const premature = await request.post('/api/rooms', { headers: { Authorization: `Bearer ${host.token}` }, data: { code: host.code, action: 'ready' } });
  expect(premature.ok()).toBe(false);
  await action({ action: 'resolve' }, host);
  await action({ action: 'resolve' }, host); // Repeated confirmation must not count twice.
  expect((await get(guest)).game!.phase).toBe('inspect');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.addInitScript(s => sessionStorage.setItem('jewel-hunt-session', JSON.stringify(s)), guest);
  await page.goto('/'); await page.reload();
  await expect(page.locator('.table-world')).toHaveAttribute('data-renderer', 'webgl', { timeout: 30000 });
  await expect(page.locator('.table-world')).toHaveAttribute('data-match-from', 'p1');
  await expect(page.locator('.table-world')).toHaveAttribute('data-match-to', 'p0');
  await expect(page.getByRole('heading', { name: 'みんなの一手を確認しよう' })).toBeVisible();
  await expect(page.getByLabel('アカリの公開した駒')).toContainText('6');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'みんなの一手を確認しよう' })).toBeVisible();
  expect((await get(guest)).game!.players[0].jewels).toHaveLength(0);
  await page.evaluate(() => scrollTo(0, 0));
  const confirmBounds = await page.getByRole('button', { name: '確認した · 得点と効果を実行' }).boundingBox();
  expect(confirmBounds!.y + confirmBounds!.height).toBeLessThan(844);
  await page.getByRole('button', { name: '確認した · 得点と効果を実行' }).click();
  await expect(page.getByRole('status', { name: '採掘ガチャ演出中' })).toBeVisible();
  await expect(page.locator('.mined-die')).toHaveCount(0);
  await expect(page.getByRole('button', { name: '次のターンへ' })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/mining-shuffle-mobile.png', fullPage: true });
  await expect(page.getByRole('status', { name: '採掘結果' })).toBeVisible();
  await expect(page.locator('.mining-prizes>div')).toHaveCount(1);
  await expect(page.locator('.mining-prizes')).toContainText('ソラ');
  await expect(page.locator('[data-ledger-player="p2"] .mined-die')).toHaveCount(0);
  await expect(page.locator('[data-ledger-player="p3"] .mined-die')).toHaveCount(0);
  await expect(page.locator('[data-ledger-player="p0"]').getByLabel('ルビー 6点 1個')).toBeVisible();
  await expect(page.locator('[data-ledger-player="p1"] .mined-die')).toBeVisible();
  const ownResult = await get(guest), otherResult = await get(host);
  const privateDraw = ownResult.game!.visualEvents!.find(e => e.type === 'mining' && e.player === guest.playerId)!;
  expect(privateDraw).toBeTruthy();
  expect(JSON.stringify(otherResult)).not.toContain(privateDraw.die.id);
  expect(otherResult.game!.visualEvents!.filter(e => e.type === 'mining')).toHaveLength(0);
  expect(otherResult.game!.miningBag).toHaveLength(0);
  await page.screenshot({ path: 'test-results/public-ledger-mobile.png', fullPage: true });
  await expect(page.getByRole('button', { name: '次のターンへ' })).toBeVisible();
  const nextBounds = await page.getByRole('button', { name: '次のターンへ' }).boundingBox();
  expect(nextBounds!.y + nextBounds!.height).toBeLessThan(844);
  await page.evaluate(() => scrollTo(0, document.body.scrollHeight));
  const stickyBounds = await page.getByRole('button', { name: '次のターンへ' }).boundingBox();
  expect(stickyBounds!.y).toBeGreaterThanOrEqual(0);
  expect(stickyBounds!.y + stickyBounds!.height).toBeLessThan(844);
  await page.getByRole('button', { name: 'アカリの宝石と使用状況を見る' }).click();
  const dialog = page.getByRole('dialog', { name: 'みんなの宝石と使用状況' });
  await expect(dialog.getByRole('tab', { name: 'アカリ' })).toHaveAttribute('aria-selected', 'true');
  await expect(dialog.getByLabel('ルビー 6点 1個')).toBeVisible();
  await expect(dialog.locator('[data-special="thief"]')).toContainText('使用済み 1 / 4');
  await expect(dialog.locator('[data-special="thief"]')).toContainText('残り 3個');
  await page.screenshot({ path: 'test-results/player-intel-mobile.png', fullPage: true });
  await dialog.getByRole('tab', { name: 'ソラ' }).click();
  await expect(dialog.locator('[data-special="poison"]')).toContainText('使用済み 1 / 2');
  await expect(dialog.locator('[data-special="mining"]')).toContainText('使用済み 1 / 4');
  await page.getByRole('button', { name: '卓に戻る' }).click();
  await action({ action: 'ready' }, host); await action({ action: 'ready' }, guest);
  await expect(page.locator('.table-world')).toHaveAttribute('data-match-to', 'p3');
  await page.waitForTimeout(800); // Let the camera and line settle for the screenshot.
  await page.screenshot({ path: 'test-results/match-guide-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.waitForTimeout(800);
  await page.screenshot({ path: 'test-results/match-guide-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'みんなの持ち物' }).click();
  await expect(dialog.getByRole('tab', { name: 'CPU 2' })).toHaveAttribute('aria-selected', 'true');
});
